### ISSUE TITLE
Roadmap for v0

### ISSUE THREAD

**Issue by mugulmd** [mugulmd/Claude#1]
Claude is at a quite early stage and have very few features, hence it is not really usable in live-coding sessions yet.

Here we can track global advancement on the features needed for a complete v0:
- [x] allow sending different data types
- [x] allow sending vectors
- [x] allow editing the input fragment shader using a file watcher
- [x] handle resolution change and full screen display

**Comment by mugulmd** [comment]
All features are ready for v0, now all that is left is code clean-up, documentation, bug fix and demo.
